
class Keywords:
    '''
    emotions = [
        acceptance
        admiration
        adoration
        affection
        afraid
        agitation
        agreeable
        aggressive
        aggravation
        agony
        alarm
        alienation
        amazement
        amusement
        anger
        angry
        anguish
        annoyance
        anticipation
        anxiety
        apprehension
        assertive
        assured
        astonishment
        attachment
        attraction
        awe
        beleaguered
        bewitched
        bitterness
        bliss
        blue
        boredom
        calculating
        calm
        capricious
        caring
        cautious
        charmed
        cheerful
        closeness
        compassion
        complacent
        compliant
        composed
        contempt
        conceited
        concerned
        content
        contentment
        crabby
        crazed
        crazy
        cross
        cruel
        defeated
        defiance
        delighted
        dependence
        depressed
        desire
        disappointment
        disapproval
        discontent
        disenchanted
        disgust
        disillusioned
        dislike
        dismay
        displeasure
        dissatisfied
        distraction
        distress
        disturbed
        dread
        eager
        earnest
        easy-going
        ecstasy
        ecstatic
        elation
        embarrassment
        emotion
        emotional
        enamored
        enchanted
        enjoyment
        enraged
        enraptured
        enthralled
        enthusiasm
        envious
        envy
        equanimity
        euphoria
        exasperation
        excited
        exhausted
        extroverted
        exuberant
        fascinated
        fatalistic
        fear
        fearful
        ferocity
        flummoxed
        flustered
        fondness
        fright
        frightened
        frustration
        furious
        fury
        generous
        glad
        gloating
        gloomy
        glum
        greedy
        grief
        grim
        grouchy
        grumpy
        guilt
        happiness
        happy
        harried
        homesick
        hopeless
        horror
        hostility
        humiliation
        hurt
        hysteria
        infatuated
        insecurity
        insulted
        interested
        introverted
        irritation
        isolation
        jaded
        jealous
        jittery
        jolliness
        jolly
        joviality
        jubilation
        joy
        keen
        kind
        kindhearted
        kindly
        laid back
        lazy
        like
        liking
        loathing
        lonely
        longing
        loneliness
        love
        lulled
        lust
        mad
        merry
        misery
        modesty
        mortification
        naughty
        neediness
        neglected
        nervous
        nirvana
        open
        optimism
        ornery
        outgoing
        outrage
        panic
        passion
        passive
        peaceful
        pensive
        pessimism
        pity
        placid
        pleased
        pride
        proud
        pushy
        quarrelsome
        queasy
        querulous
        quick-witted
        quiet
        quirky
        rage
        rapture
        rejection
        relief
        relieved
        remorse
        repentance
        resentment
        resigned
        revulsion
        roused
        sad
        sadness
        sarcastic
        sardonic
        satisfaction
        scared
        scorn
        self-assured
        self-congratulatory
        self-satisfied
        sentimentality
        serenity
        shame
        shock
        smug
        sorrow
        sorry
        spellbound
        spite
        stingy
        stoical
        stressed
        subdued
        submission
        suffering
        surprise
        sympathy
        tenderness
        tense
        terror
        threatening
        thrill
        timidity
        torment
        tranquil
        triumphant
        trust
        uncomfortable
        unhappiness
        unhappy
        upset
        vain
        vanity
        venal
        vengeful
        vexed
        vigilance
        vivacious
        wary
        watchfulness
        weariness
        weary
        woe
        wonder
        worried
        wrathful
        zeal
        zest
    ]
    '''

    fastfood = [
        "burrito",
        "chips",
        "fries",
        "hamburger",
        "hot dog",
        "nacho",
        "nugget",
        "onion rings",
        "pizza",
        "sandwich",
        "sausage",
        "taco"
    ]

    fruits = [
        "apple",
        "apricot",
        "avocado",
        "banana",
        "berry",
        "blackberry",
        "blood orange",
        "blueberry",
        "boysenberry",
        "breadfruit",
        "cantaloupe",
        "cherry",
        "citron",
        "citrus",
        "coconut",
        "crabapple",
        "cranberry",
        "current",
        "date",
        "dragonfruit",
        "durian",
        "elderberry",
        "fig",
        "grape",
        "grapefruit",
        "guava",
        "honeydew",
        "jackfruit",
        "kiwi",
        "kumquat",
        "lemon",
        "lime",
        "lingonberry",
        "loquat",
        "lychee",
        "mandarin",
        "mango",
        "mangosteen",
        "marionberry",
        "melon",
        "mulberry",
        "nectarine",
        "orange",
        "papaya",
        "passion fruit",
        "peach",
        "pear",
        "persimmon",
        "pineapple",
        "plantain",
        "plum",
        "pluot",
        "pomegranite",
        "pomelo",
        "prune",
        "quince",
        "raisin",
        "rambutan",
        "raspberry",
        "starfruit",
        "strawberry",
        "tangelo",
        "tangerine",
        "ugli fruit",
        "watermelon"
    ]

    meat = [
        "bacon",
        "beef",
        "chicken",
        "duck",
        "ham",
        "mutton",
        "pork",
        "sausage",
        "steak",
        "turkey",
        "veal",
        "venison",
    ]

    seafood = [
        "abalone",
        "anchovy",
        "bass",
        "caviar",
        "clam",
        "cockle",
        "cod",
        "crab",
        "crayfish",
        "eel",
        "gemfish",
        "herring",
        "lobster",
        "mackerel",
        "mussel",
        "octopus",
        "oyster",
        "prawn",
        "salmon",
        "sardine",
        "scallop",
        "sea cucumber",
        "shark",
        "shellfish",
        "shrimp",
        "squid",
        "trout",
        "tuna"
    ]

    vegetables = [
        "acorn squash",
        "alfalfa",
        "artichoke",
        "arugula",
        "asparagus",
        "avocado",
        "bamboo shoots",
        "basil",
        "beans",
        "beets",
        "bell pepper",
        "black-eyed peas",
        "broccoli",
        "brussels sprouts",
        "capers",
        "carrot",
        "cauliflower",
        "celeriac",
        "celery",
        "chard",
        "chick peas",
        "chinese cabbage",
        "chives",
        "collard greens",
        "cress",
        "cucumber",
        "daikon",
        "dandelion greens",
        "eggplant",
        "endive",
        "fava bean",
        "fennel",
        "garlic",
        "ginger",
        "gourd",
        "greenbean",
        "greens",
        "hot chile peppers",
        "iceberg lettuce",
        "jicama",
        "kale",
        "kohlrabi",
        "leek",
        "lentils",
        "lettuce",
        "lima bean",
        "maize",
        "mung bean",
        "mushroom",
        "mustard greens",
        "okra",
        "olive",
        "onion",
        "parsley",
        "parsnip",
        "pattypan squash",
        "pea",
        "peapod",
        "peanut",
        "peppers",
        "pickle",
        "potato",
        "pumpkin",
        "radicchio",
        "radish",
        "rhubarb",
        "rocket",
        "romaine",
        "rutabaga",
        "salad",
        "salsa",
        "scallion",
        "seaweed",
        "shallot",
        "sorrel",
        "soybean",
        "spinach",
        "sprouts",
        "salsify",
        "spuds",
        "squash",
        "string bean",
        "succotash",
        "sweet potato",
        "swiss chard",
        "taro",
        "tomatillo",
        "tomato",
        "tuber",
        "turnip",
        "vegetable",
        "wasabi",
        "water chestnut",
        "watercress",
        "yam",
        "zucchini",
    ]
