- hosts: database
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: Add couchdb repository
      apt_repository:
        repo: deb https://apache.bintray.com/couchdb-deb xenial main
        state: present

    - name: Install Apache CouchDB
      apt:
        name: couchdb
        state: latest
        update_cache: yes
        allow_unauthenticated: yes

    - name: Change couchdb configure file ownership
      file: 
          path: /opt/couchdb
          owner: couchdb
          group: couchdb
          mode: 0777
          recurse: yes
          state: directory

    - name: Install couchdb library for python
      pip:
        name: cloudant
        executable: pip3

    - name: Bind couchdb port to public
      lineinfile:
        dest: /opt/couchdb/etc/local.ini
        line: "{{ item.option }}={{ item.value }}"
        insertafter: '\[chttpd\]'
      with_items:
        - { option: bind_address, value: 0.0.0.0 }
        - { option: port, value: 5984 }

    - name: Add default admin account "aassddff" to couchdb
      lineinfile:
        dest: /opt/couchdb/etc/local.ini
        line: "aassddff = ffddssaa"
        insertafter: '^\[admins\]$'

    - name: Change ip bind configuration in default.ini
      replace:
        dest: /opt/couchdb/etc/default.ini
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Change node ipaddress in cluster configuration
      replace:
        dest: /opt/couchdb/etc/vm.args
        regexp: '^-name couchdb@127.0.0.1'
        replace: '-name couchdb@{{ ansible_eth0.ipv4.address }}'

    - name: Restart couchdb service
      service:
        name: couchdb
        state: restarted
